version: 2.1

workflow:
  build:
    jobs:
      docker:
        - image: circleci/node:12.14.1

      working_directory: ~/repo

      steps:
        - checkout
        - npm install
        - npm test
